apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-gluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gluster
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-gluster
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        volumeMounts:
        - mountPath: /root
          name: storage
          readOnly: false
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: gluster-pvc
