apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: server
spec:
  replicas: 3
  serviceName: server-ss
  selector:
    matchLabels:
      role: server
  template:
    metadata:
      labels:
        role: server
    spec:
      containers:
      - name: server
        image: nginx
        volumeMounts:
          - mountPath: /var/lib/www/html
            name: mypvc
  volumeClaimTemplates:
  - metadata:
      name: mypvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: gluster
      resources:
        requests:
          storage: 8Gi
