kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  annotations:
    name: "wx"
    company: "qingcloud"
    project: "kubesphere"
provisioner: kubernetes.io/rbd
reclaimPolicy: Delete
parameters:
  monitors: 192.168.1.3:6789,192.168.1.4:6789,192.168.1.5:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: default
  pool: rbd
  userId: admin
  userSecretName: ceph-secret-user
  fsType: ext4
  imageFormat: "1"
allowVolumeExpansion: true
