apiVersion: v1
kind: Service
metadata:
  name: server-ss
  labels:
    role: server
spec:
  ports:
  - name: nginx
    port: 8080
  clusterIP: None
  selector:
    role: server
---
apiVersion: v1
kind: Service
metadata:
  name: server-ss-read
  labels:
    role: server
spec:
  ports:
  - name: nginx
    port: 8080
  selector:
    role: server
