
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher-qingcloud

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-qingcloud
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-qingcloud
subjects:
  - kind: ServiceAccount
    name: csi-attacher-qingcloud
    namespace: default
roleRef:
  kind: ClusterRole
  name: csi-attacher-qingcloud
  apiGroup: rbac.authorization.k8s.io
---

kind: Service
apiVersion: v1
metadata:
  name: csi-attacher-qingcloud
  labels:
    app: csi-attacher-qingcloud
spec:
  selector:
    app: csi-attacher-qingcloud
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-attacher-qingcloud
spec:
  serviceName: "csi-attacher-qingcloud"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher-qingcloud
    spec:
      serviceAccount: csi-attacher-qingcloud
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-qingcloud/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-qingcloud
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-qingcloud
            type: DirectoryOrCreate
