apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  persistentVolumeReclaimPolicy: Delete
  nfs:
    # FIXME: use the right IP
    server: 192.168.1.5
    path: "/home/pv-nfs"
