kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rwx
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: gluster
