kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rox
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: gluster
