apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
  labels:
    app: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: time
            operator: In
            values:
            - new
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
